export const browserCoreExamples = [
  "mouse browser status",
  "mouse browser start",
  "mouse browser stop",
  "mouse browser tabs",
  "mouse browser open https://example.com",
  "mouse browser focus abcd1234",
  "mouse browser close abcd1234",
  "mouse browser screenshot",
  "mouse browser screenshot --full-page",
  "mouse browser screenshot --ref 12",
  "mouse browser snapshot",
  "mouse browser snapshot --format aria --limit 200",
  "mouse browser snapshot --efficient",
  "mouse browser snapshot --labels",
];

export const browserActionExamples = [
  "mouse browser navigate https://example.com",
  "mouse browser resize 1280 720",
  "mouse browser click 12 --double",
  'openclaw browser type 23 "hello" --submit',
  "mouse browser press Enter",
  "mouse browser hover 44",
  "mouse browser drag 10 11",
  "mouse browser select 9 OptionA OptionB",
  "mouse browser upload /tmp/openclaw/uploads/file.pdf",
  'openclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "mouse browser dialog --accept",
  'openclaw browser wait --text "Done"',
  "mouse browser evaluate --fn '(el) => el.textContent' --ref 7",
  "mouse browser console --level error",
  "mouse browser pdf",
];
